name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      upload:
        required: false
        type: boolean
        default: false
      sign:
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      upload:
        required: false
        type: boolean
        default: false
      sign:
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: '0'
      - name: Set up JDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          java-version: '17.0.10'
          distribution: 'liberica'
          architecture: 'x64'
      - uses: gradle/wrapper-validation-action@b5418f5a58f5fd2eb486dd7efb368fe7be7eae45 # v2.1.3
      - name: Set up Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
        with:
          generate-job-summary: true
          dependency-graph: generate-and-submit
      - name: Install cosign
        if: ${{ inputs.sign }}
        uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5 # v3.10.1
        with:
          cosign-release: 'v2.6.5'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build
        env:
          ORG_GRADLE_PROJECT_projectVersion: ${{ inputs.version }}
          QUARKUS_PACKAGE_TYPE: "uber-jar"
        run: ./gradlew build
      - name: Integration tests
        env:
          ORG_GRADLE_PROJECT_projectVersion: ${{ inputs.version }}
          QUARKUS_PACKAGE_TYPE: "uber-jar"
        run: ./gradlew quarkusIntTest
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-reports
          path: |
            build/reports/
            !build/reports/configuration-cache
      - name: Upload jar
        if: ${{ inputs.upload }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pulsar-bookie-utils-${{ inputs.version }}.jar
          path: build/quarkus-build/gen/pulsar-bookie-utils-${{ inputs.version }}-runner.jar
      - name: Rename jar
        run: mv "build/pulsar-bookie-utils-${{ inputs.version }}-runner.jar" "pulsar-bookie-utils-${{ inputs.version }}.jar"
      - name: Add jar to release
        if: ${{ github.event_name == 'release' && inputs.upload }}
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          tag_name: ${{ inputs.version }}
          files: |
            pulsar-bookie-utils-${{ inputs.version }}.jar
      - name: Build fast-jar for container
        env:
          ORG_GRADLE_PROJECT_projectVersion: ${{ inputs.version }}
          QUARKUS_PACKAGE_TYPE: "fast-jar"
        run: ./gradlew build
      - name: Registry login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.upload }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Sign image
        if: ${{ inputs.sign }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

