name: OWASP
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: '0'
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: '17.0.10'
          distribution: 'liberica'
          architecture: 'x64'
      - uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0
      - name: Set up Gradle
        uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v3.1.0
        with:
          generate-job-summary: true
          dependency-graph: generate-and-submit

      - name: OWASP dependency check
        env:
          ORG_GRADLE_PROJECT_projectVersion: ${{ inputs.version }}
          ORG_GRADLE_PROJECT_nvdApiKey: ${{ secrets.NVD_API_KEY }}
          GRADLE_OPTS: -Xmx8g
        run: ./gradlew dependencyCheckAggregate
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: owasp-reports
          path: |
            build/reports/
            !build/reports/configuration-cache
